# travis-ci
language: go
go_import_path: aqwari.net/xml
go:
  - 1.10.x
  - master
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
